apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-images
spec:
  background: true
  rules:
  - match:
      resources:
        kinds:
        - Pod
    name: verify-notary-signature
    verifyImages:
    - imageReferences:
      - ghcr.io/kubeconchina2023/test-verify-image*
      type: Notary
      attestors:
      - count: 1
        entries:
        - certificates:
            # invalid cert
            cert: |-
              -----BEGIN PUBLIC KEY-----
              MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE8nXRh950IZbRj8Ra/N9sbqOPZrfM
              5/KAQN0/KjHcorm/J5yctVd7iEcnessRQjU917hmKO6JWVGHpDguIyakZA==
              -----END PUBLIC KEY-----
            # cert: |-
            #   -----BEGIN CERTIFICATE-----
            #   MIIDWDCCAkCgAwIBAgIBPDANBgkqhkiG9w0BAQsFADBbMQswCQYDVQQGEwJVUzEL
            #   MAkGA1UECBMCV0ExEDAOBgNVBAcTB1NlYXR0bGUxDzANBgNVBAoTBk5vdGFyeTEc
            #   MBoGA1UEAxMTa3ViZWNvbmNoaW5hMjAyMy5pbzAeFw0yMzA5MjYxNjA0MzlaFw0y
            #   MzA5MjcxNjA0MzlaMFsxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEQMA4GA1UE
            #   BxMHU2VhdHRsZTEPMA0GA1UEChMGTm90YXJ5MRwwGgYDVQQDExNrdWJlY29uY2hp
            #   bmEyMDIzLmlvMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvwADS720
            #   v01MmCbJSaGItLjG2eKiU9JarvXLGtKY+5SoBtfdeX0XvtQQfgigd6X26/xYPkaD
            #   sHScZ6mqFmagO5cNHhcFacXDnSK+HKIC6ka3WdFW5ltvMAP6ObpiMTIu5NL4yZgv
            #   JGQqOm2WzAAYn26dfGLfGafOUsUHJoayhcT2fltV+Gldp612Hk9jGeLcdiWU9BL8
            #   0/uF1C6/b6KUXc1MR67M5Of3fK7GoyG0dPuTjWWHwi0E7p28KDmVCZjM4MxD+T4Z
            #   fIXI5TzNxS4ldYLpVMpAN8SwQolu1JU4quzCGUJ/mM8NRZw7XVt9Ym1E05B2sKj0
            #   NhX4qLxsqtbVhwIDAQABoycwJTAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAwwCgYI
            #   KwYBBQUHAwMwDQYJKoZIhvcNAQELBQADggEBAGLN1KkV8fG+IUXRffSHdlR064Ir
            #   RR0Kr36L+ok2zkr9ArT0G5JY5dVxmUOpwHJvw9y0Wt1yUptszsZCDPLf8ZscTmpa
            #   ziNgWyjx+1PoLOMgASAHFyeqjReVRLVxrTWigw1+MLlkEDnT2DFoezsR5u5xnLk+
            #   d2TGM6CX+y2iLpxTJZkmcqxqm5+ps1U2/SxfVRkEnmLVSnsqOKA112ryuB7KI2Il
            #   rpbHq/PGIqK0GDHHrZFJRIPtO/oYtCTPXU6xrvHt0m/x3fB6xRtcX/Quni3s0xCJ
            #   jSOvSdjEwoCknVfNd6LKPi6sjZm6pLKM58Adekk4Qq5+6M0w/EB+AMwV2Qc=
            #   -----END CERTIFICATE-----
      mutateDigest: true
      required: true
      verifyDigest: true
  validationFailureAction: Enforce
  webhookTimeoutSeconds: 30