apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-images
spec:
  background: true
  rules:
  - match:
      resources:
        kinds:
        - Pod
    name: verify-notary-signature
    verifyImages:
    - imageReferences:
      - ghcr.io/kubeconchina2023/sign-action-demo*
      type: Notary
      attestors:
      - count: 1
        entries:
        - certificates:
            # cert: |-
            #   -----BEGIN CERTIFICATE-----
            #   MIIDsDCCApigAwIBAgIQI397yUzzS3avqhnAwpbsXDANBgkqhkiG9w0BAQsFADBaMQswCQYDVQQG
            #   EwJVUzELMAkGA1UECBMCV0ExEDAOBgNVBAcTB1NlYXR0bGUxDzANBgNVBAoTBk5vdGFyeTEbMBkG
            #   A1UEAxMSd2FiYml0LW5ldHdvcmtzLmlvMB4XDTIzMDIxMjE2MDM0OFoXDTI0MDIxMjE2MTM0OFow
            #   WjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAldBMRAwDgYDVQQHEwdTZWF0dGxlMQ8wDQYDVQQKEwZO
            #   b3RhcnkxGzAZBgNVBAMTEndhYmJpdC1uZXR3b3Jrcy5pbzCCASIwDQYJKoZIhvcNAQEBBQADggEP
            #   ADCCAQoCggEBAMUOvS3Kgr2ojXOf5i4G1eltX4c5jOXeZPlRk4t1LTLj3xt+OFObwIq3gKVxk++Z
            #   wztJND4JeCk5X7uTridZ6Ev77IcbvjFhfcdi24AB+A0O9H8dP2o/HzX4XuR18fW6VPrbIwDxb72H
            #   SJmOZthjikIJhcvitDmvo8/yYBQsRxzpfR/ajkbsTuH4b20EJKyIplJSQEbzvLtb2dj7H8xK69m3
            #   noVEZnHI2xH9jRhk01Km1ma6i2FpVrOClw+uifdnDLR9p91wRQteQPQDnd0yrubxe/wsz7074w5Q
            #   4fmUbxWsa1SWtuvS420BC3Mgy1hBlEBHkm71WMxMIzmRsL5eVJ0CAwEAAaNyMHAwDgYDVR0PAQH/
            #   BAQDAgeAMAkGA1UdEwQCMAAwEwYDVR0lBAwwCgYIKwYBBQUHAwMwHwYDVR0jBBgwFoAUlgxd45NG
            #   zrE+qAjXo2JPTylwrzwwHQYDVR0OBBYEFJYMXeOTRs6xPqgI16NiT08pcK88MA0GCSqGSIb3DQEB
            #   CwUAA4IBAQDBcR+m48f8qilFLmzAt0fACeEpj1xHAbS6KCF741pgUCYoNWo/ALMxN3RdJgTbR7qk
            #   6bER63Ql+pEJUHg/tUFfKx9nv0A5DqFbwe4PNwc9nF5KSJpaZrWm6qccr8N5OPOGarSWU3Wg+DQx
            #   aE67PToGTI2KTajhYuQVX+y/kgX9zP3DggtG2WiPrIUSJrZFEZM7WVPVnvWCUZEa+NPq3byMJGIM
            #   ir+zzBKLSIf4mfn227tBPbowOjjVecV5WEzKItUYLvHtk3kWP+dMeQY/AuIo/yhvvCTA2e4OKDyZ
            #   sR7TpO9qCHsFGcv4S+iYT6quz/6S+0VRkOPUc/7bm/9OAws1
            #   -----END CERTIFICATE-----
            # # invalid cert
            cert: |-
              -----BEGIN PUBLIC KEY-----
              MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE8nXRh950IZbRj8Ra/N9sbqOPZrfM
              5/KAQN0/KjHcorm/J5yctVd7iEcnessRQjU917hmKO6JWVGHpDguIyakZA==
              -----END PUBLIC KEY-----
      mutateDigest: true
      required: true
      verifyDigest: true
  validationFailureAction: Enforce
  webhookTimeoutSeconds: 30